[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/api/*"
  to = "https://feedflow-news.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200